name: Auto Download and Update TV

on:
  schedule:
    - cron: "0 */6 * * *"   # Run every 6 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Download file
        run: |
          DOWNLOAD_URL="https://vnnhan.com/tv.m3u8"
          OUTPUT_PATH="tv.m3u8"

          mkdir -p "$(dirname "$OUTPUT_PATH")"
          curl -L "$DOWNLOAD_URL" -o "$OUTPUT_PATH"

      - name: Commit changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-update TV"
            git push
          else
            echo "No changes detected."
          fi
